# Generated by Django 3.1.6 on 2021-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210509_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catogory',
            field=models.CharField(choices=[('sciencebook', 'sciencebook'), ('mathbook', 'mathbook'), ('english', 'english')], max_length=20, null=True),
        ),
    ]
